name: Build
on: push
jobs:
  # Builds the docker image to be used in subsequent jobs
  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v2
      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # So now you can use Actions' own caching!
      - name: Restore Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: mikedidomizio/mikedidomizio.com:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  # Run the test coverage
  test:
    needs: [build_docker_image]
    name: Run test suites
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # So now you can use Actions' own caching!
      - name: Restore Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: mikedidomizio/mikedidomizio.com:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/mikedidomizio-image.tar
      - name: Docker load the tar file
        run: |
          docker image load --input /tmp/mikedidomizio-image.tar
      - name: Run tests
        run: |
          ./scripts/run-tests-for-coverage.sh mikedidomizio/mikedidomizio.com:latest
      # use hash for safety reasons, using master/tags can introduce security risks into workflow
      - name: Push Code Coverage
        uses: codecov/codecov-action@2838b54ec211d3f145409dbf867d4b3f22af4637
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # optional (default = false)
          verbose: false # optional (default = false)
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # Uses the docker image to build the product
  build:
    needs: [test]
    if: github.ref == 'refs/heads/master'
    name: Build product for deployment
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # So now you can use Actions' own caching!
      - name: Restore Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: mikedidomizio/mikedidomizio.com:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/mikedidomizio-image.tar
      - name: Docker load the tar file
        run: |
          docker image load --input /tmp/mikedidomizio-image.tar
      - name: Build for production
        run: |
          ./scripts/build.sh mikedidomizio/mikedidomizio.com:latest

      - name: Save build artifacts for pushing to S3 in deploy job
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: build-deploy
          path: dist/

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # Deploys the website to S3
  deploy:
    # the following is only done if the branch is master
    needs: [build]
    if: github.ref == 'refs/heads/master'
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      # when we download the artifacts it deploys into the current directory
      - name: Download build for deploy
        uses: actions/download-artifact@v2
        with:
          name: build-deploy

      - name: Configure AWS credentials
        # use hash for safety reasons, using master/tags can introduce security risks into workflow
        uses: aws-actions/configure-aws-credentials@51e2d042f8c5cf77f151685c9338e989dc0b8fc8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --exclude "package*.json" --acl public-read
