name: Upload Website
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout
      - name: Deploy static site to S3 bucket
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # sync to S3, ignore files/folders that we don't need to store in s3
        run: aws s3 sync ./ s3://www.mikedidomizio.com --exclude ".git*" --exclude ".idea*" --acl public-read
