name: Upload Website
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
        name: Checkout
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build image and test
        run: docker build -t mikedidomizio:mikedidomizio.com .
      - name: Install dependencies
        run: |
          # install yarn since we use yarn for lockfiles
          npm install -g yarn
          yarn install
          yarn build
      - name: Run code coverage
        run: yarn test:unit
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Build production version
        run: yarn build
      - name: Deploy static site to S3 bucket
        if: github.ref == 'refs/heads/master'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./dist s3://www.mikedidomizio.com --exclude "package*.json" --acl public-read
